# Azure Pipelines YAML file for Angular-Python Application

parameters:
- name: gitUsername
  type: string
  default: AishwaryaaRaghuraman
- name: repoName
  type: string
  default: angular_python
- name: branchName
  type: string
  default: main

trigger:
- main

pool: Default


steps:
- script: echo "Git Clone"
  displayName: 'Git Clone'
  env:
    GIT_USERNAME: $(gitUsername)
    REPO_NAME: $(repoName)
    BRANCH_NAME: $(branchName)
  continueOnError: false

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js 18.x'

- script: |
    echo Installing for build
    cd frontend/
    npm install -g @angular/cli
    npm install
    ng version
    ng build  
  displayName: 'npm install and build'

- script: |
    echo Starting the build
    cd frontend/
    ng build  
  displayName: 'Build with Angular'

- script: |
    echo Install 
    cd backend/
 
    python -m venv venv
    .\venv\Scripts\activate 
    pip install -r requirements.txt
  displayName: 'installing '

- script: |
    echo Starting the build
    cd backend/
    python main.py
  displayName: 'Build with Python'

- script: |
    echo "Running SonarQube Scan"
    sonar-scanner.bat -D"sonar.projectKey=$(projectkey)" -D"sonar.sources=." -D"sonar.host.url=$(SONAR_URL)" -D"sonar.token=$(SONAR_TOKEN)" 
    displayName: 'Run SonarQube Scanning'


- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/frontend/dist/'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'